import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from '@/context/AuthContext'
import { LoaderProvider } from '@/context/LoaderContext';
import GlobalLoader from '@/components/(sheared)/GlobarLoader';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LoaderProvider>
      <GlobalLoader />

      <html lang="en">
        <body
          className="!font-body bg-gc-600"
        >
          <AuthProvider>
            {children}
          </AuthProvider>
        </body>
      </html>

    </LoaderProvider>
  );
}
